version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11

executors:
  node:
    docker:
      - image: circleci/node:12.6.0 
  python:
    docker:
      - image: circleci/python:2.7

jobs:
  build:
    working_directory: ~/flex-plugin-starter
    executor: node
    parameters:
      stage_name:
        type: string
    steps:
      - checkout
      - run: cp public/appConfig.example.js public/appConfig.js
      - run: sed -i "s/\'accountSid\'/\'<< parameters.stage_name >>_${ACCOUNT_SID}\'/g" public/appConfig.js
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test
      - run: npm run build
      - store_artifacts: {path: build}
      - persist_to_workspace:
          root: .
          paths:
            - build 

  deploy-plugin:
    executor: python 
    steps:
      - checkout
      - attach_workspace: {at: .}
      - aws-s3/sync:
          from: build
          to: s3://flex-plugin-starter/dist/<< parameters.stage_name >>/
          overwrite: true 

      - run:
          name: Rollbar notification
          command: |
            curl https://api.rollbar.com/api/1/deploy/ \
                -F access_token=${ROLLBAR_TOKEN} \
                -F environment=<< parameters.stage_name >> \
                -F revision=${CIRCLE_SHA1} \
                -F rollbar_username=${CIRCLE_USERNAME} \
                -F local_username=${CIRCLE_USERNAME} \
                -F comment="${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BRANCH} by ${CIRCLE_USERNAME}"

workflows:
  version: 2.1
  build-deploy:
    jobs:
      # non-master branches deploy to the 'dev' stage
      - deploy-plugin:
          - build
          name: Deploy Plugin DEV
          stage_name: dev
          context: Development
          filters:
            branches:
              ignore: master

      # master branch deploy to the 'prod' stage
      - deploy-plugin:
          - build
          name: Deploy Plugins PRD
          stage_name: prd
          context: Production
          filters:
            branches:
              only: master

